// Admin panel texts: Spanish (the key) → English. See lib/adminText/index.ts.
export const appearance = {
  // Editor (AppearanceEditor, PreviewFrame)
  "Estilos": "Styles",
  "Datos de la tienda": "Store data",
  "PC": "PC",
  "Móvil": "Mobile",
  "Partes del editor": "Editor parts",
  "Dispositivo": "Device",
  "Cambios sin publicar": "Unpublished changes",
  "Cambios publicados en la tienda": "Changes published to the store",
  "No se pudo guardar el borrador. Se intentará de nuevo con tu próximo cambio.": "The draft could not be saved. It will be tried again with your next change.",
  "¿Descartar los cambios sin publicar?": "Discard the unpublished changes?",
  "Seguir editando": "Keep editing",
  "Hay campos por corregir en una sección. Los cambios del inicio no se guardan hasta corregirlos.": "Some fields in a section need fixing. Home changes are not saved until you fix them.",
  "Logo y nombre": "Logo and name",
  "Contacto": "Contact",
  "Redes sociales": "Social media",
  "Vista previa de la tienda": "Store preview",

  // Store data (IdentitySection, BannerSection, ContactSection, SocialSection)
  "Nombre de la tienda": "Store name",
  "Eslogan": "Tagline",
  "Logo": "Logo",
  "Texto principal": "Main text",
  "Texto secundario": "Secondary text",
  "Imagen del logo": "Logo image",
  "Favicon": "Favicon",
  "Etiqueta": "Label",
  "Parte resaltada del título": "Highlighted part of the title",
  "Subtítulo": "Subtitle",
  "Botón principal": "Main button",
  "Botón secundario": "Secondary button",
  "{button}: texto": "{button}: text",
  "Valor": "Value",
  "Soporte": "Support",
  "Cifras (máximo {max})": "Figures (up to {max})",
  "Quitar cifra": "Remove figure",
  "+ Agregar cifra": "+ Add figure",
  "Correo": "Email",
  "Teléfono": "Phone",
  "Dirección": "Address",
  "Horario": "Hours",
  "Los campos vacíos no se muestran en la tienda.": "Empty fields are not shown in the store.",
  "Pega el enlace de cada red que uses. Las vacías no se muestran.": "Paste the link for each network you use. Empty ones are not shown.",

  // Pages (PagesTab, BlockEditor, paginas/page.tsx, lib/validation.ts)
  "Contenido de Sobre nosotros, Términos, Privacidad, Preguntas frecuentes y Ayuda.": "Content for About us, Terms, Privacy, FAQs and Help.",
  "Nosotros": "About us",
  "Términos": "Terms",
  "Privacidad": "Privacy",
  "Preguntas frecuentes": "FAQs",
  "Ayuda": "Help",
  "Ver página": "View page",
  "Tienes cambios sin guardar. ¿Descartarlos?": "You have unsaved changes. Discard them?",
  "Introducción": "Introduction",
  "Separa los párrafos con una línea en blanco.": "Separate paragraphs with a blank line.",
  "Bloque {n}": "Block {n}",
  "Subir bloque": "Move block up",
  "Bajar bloque": "Move block down",
  "Eliminar bloque": "Delete block",
  "Ícono": "Icon",
  "Enlace (opcional)": "Link (optional)",
  "+ Agregar bloque": "+ Add block",
  "Camión": "Truck",
  "Escudo": "Shield",
  "Audífonos": "Headset",
  "Estrella": "Star",
  "Carrito": "Cart",
  "Tarjeta": "Card",
  "Paquete": "Package",
  "Devolución": "Return",
  "Lista": "List",
  "Documento": "Document",
  "Usuario": "User",
  "Candado": "Lock",
  "Cookie": "Cookie",

  // Home sections (SectionList, SectionForm, lib/homeSections.ts)
  "Banner principal": "Main banner",
  "Productos por tipo": "Products by type",
  "Blog": "Blog",
  "Imagen con texto": "Image with text",
  "Franja promocional": "Promo strip",
  "Productos elegidos": "Selected products",
  "Texto libre": "Free text",
  "Testimonios": "Testimonials",
  "Suscripción al boletín": "Newsletter signup",
  "Una foto con título, texto y botón.": "A photo with a title, text and a button.",
  "Una franja de color para destacar una oferta.": "A color strip to highlight an offer.",
  "Productos de una categoría, destacados o en oferta.": "Products from a category, featured or on sale.",
  "Un bloque de texto libre.": "A block of free text.",
  "Opiniones de tus clientes con estrellas.": "Customer reviews with stars.",
  "Formulario para suscribirse al boletín.": "A form to subscribe to the newsletter.",
  "Una categoría": "One category",
  "Destacados": "Featured",
  "En oferta": "On sale",
  "Principal": "Primary",
  "Acento": "Accent",
  "Secundario": "Secondary",
  "Arrastrar para mover": "Drag to move",
  "Incompleta: no se muestra en la tienda": "Incomplete: not shown in the store",
  "Incompleta": "Incomplete",
  "Mover arriba": "Move up",
  "Mover abajo": "Move down",
  "Mostrar": "Show",
  "Ocultar": "Hide",
  "Secciones del inicio": "Home sections",
  "Llegaste al máximo de {max} secciones.": "You reached the limit of {max} sections.",
  "Agregar sección": "Add section",
  "Testimonio {n}": "Testimonial {n}",
  "Quitar testimonio": "Remove testimonial",
  "Opinión": "Review",
  "Estrellas": "Stars",
  "1 estrellas": "1 star",
  "{n} estrellas": "{n} stars",
  "Foto (opcional)": "Photo (optional)",
  "+ Agregar testimonio": "+ Add testimonial",
  "Texto": "Text",
  "Enlace": "Link",
  "Botón: texto": "Button: text",
  "Cuántas mostrar (3 a 12)": "How many to show (3 to 12)",
  "Cuántas entradas (1 a 6; vacío = todas las recientes)": "How many posts (1 to 6; empty = all recent)",
  "Imagen a la": "Image on the",
  "Izquierda": "Left",
  "Derecha": "Right",
  "Centro": "Center",
  "Color de fondo": "Background color",
  "Imagen de fondo (opcional)": "Background image (optional)",
  "Categoría": "Category",
  "Elige una categoría": "Choose a category",
  "Cuántos": "How many",
  "Alineación": "Alignment",
  "Texto (deja una línea en blanco entre párrafos)": "Text (leave a blank line between paragraphs)",
  "← Secciones": "← Sections",
  "La categoría elegida ya no existe; elige otra.": "The chosen category no longer exists; choose another.",
  "Sube una imagen para que esta sección se vea en la tienda.": "Upload an image so this section shows in the store.",
  "Escribe un título para que esta sección se vea en la tienda.": "Write a title so this section shows in the store.",
  "Elige una categoría para que esta sección se vea en la tienda.": "Choose a category so this section shows in the store.",
  "Escribe el texto para que esta sección se vea en la tienda.": "Write the text so this section shows in the store.",
  "Agrega al menos un testimonio para que esta sección se vea en la tienda.": "Add at least one testimonial so this section shows in the store.",
  "¿Quitar esta sección del inicio?": "Remove this section from the home page?",
  "Quitar sección": "Remove section",
  "Faltan secciones: {list}": "Missing sections: {list}",
  "Lista de secciones inválida": "Invalid section list",
  "Máximo {max} secciones": "Up to {max} sections",
  "Máximo {max} testimonios": "Up to {max} testimonials",
  "Sección repetida o inválida": "Duplicate or invalid section",
  "Tipo de sección desconocido": "Unknown section type",
  "Esta sección ya está en el inicio": "This section is already on the home page",
  "Esa categoría ya no existe": "That category no longer exists",

  // Styles (StylesPanel, ThemePicker, lib/styles.ts, constants/themes.ts)
  "1 · Paleta": "1 · Palette",
  "Paleta personalizada ·": "Custom palette ·",
  "Volver a la paleta": "Back to the palette",
  "2 · Colores": "2 · Colors",
  "El texto blanco puede leerse mal sobre: {list}.": "White text may be hard to read on: {list}.",
  "3 · Tipografía": "3 · Typography",
  "Títulos": "Headings",
  "Así se ven tus títulos": "This is how your headings look",
  "Textos": "Body text",
  "Y así el resto de los textos.": "And this is the rest of your text.",
  "4 · Esquinas": "4 · Corners",
  "5 · Botones": "5 · Buttons",
  "Principal · títulos y menú": "Primary · headings and menu",
  "Botones": "Buttons",
  "Acento · ofertas e insignias": "Accent · deals and badges",
  "Fondo": "Background",
  "Rectas": "Square",
  "Suaves": "Soft",
  "Redondas": "Round",
  "Rellenos": "Filled",
  "Con borde": "Outline",
  "Color inválido": "Invalid color",
  "Esmeralda": "Emerald",
  "Océano": "Ocean",
  "Violeta": "Violet",
  "Carmesí": "Crimson",
  "Rosa": "Pink",
  "Pizarra": "Slate",
  "Ámbar": "Amber",
  "Menta": "Mint",
  "Atardecer": "Sunset",
  "Índigo": "Indigo",
  "Cobalto": "Cobalt",
  "Bosque": "Forest",
  "Lavanda": "Lavender",
  "Coral": "Coral",
  "Medianoche": "Midnight",
  "Arena": "Sand",
} as const;
