// Admin panel texts: Spanish (the key) → English. See lib/adminText/index.ts.
export const catalog = {
  // Validators and actions (lib/catalog.ts, actions/catalog.ts)
  "Solo minúsculas, números y guiones (máx. 96)": "Lowercase letters, numbers and hyphens only (max. 96)",
  "Número inválido": "Invalid number",
  "Imagen inválida": "Invalid image",
  "Máximo {max} fotos": "Up to {max} photos",
  "Categoría inválida": "Invalid category",
  "Marca inválida": "Invalid brand",
  "Ya existe otro con este slug": "Another one already uses this slug",
  "La usa 1 producto": "Used by 1 product",
  "La usan {n} productos": "Used by {n} products",
  "Completa los campos marcados antes de publicar": "Fill in the marked fields before publishing",
  "Hubo una venta mientras publicabas; inténtalo de nuevo": "A sale happened while you were publishing; try again",
  "Este producto tiene pedidos; archívalo en lugar de borrarlo": "This product has orders; archive it instead of deleting it",
  "No hay cambios para publicar": "There are no changes to publish",
  "Producto inexistente": "Product not found",
  // Fixed labels
  "Nuevo": "New",
  "Popular": "Popular",
  "Oferta": "Sale",
  "Gadget": "Gadget",
  "Electrodomésticos": "Appliances",
  "Refrigeradores": "Refrigerators",
  "Otros": "Other",
  "Publicado": "Published",
  "Borrador": "Draft",
  "Por publicar": "To publish",
  "Archivado": "Archived",
  // Products list
  "Activos": "Active",
  "Archivados": "Archived",
  "Buscar por nombre": "Search by name",
  "No hay productos aquí.": "No products here.",
  "Sin nombre": "No name",
  "{n} u.": "{n} pcs",
  "Anterior": "Previous",
  "Siguiente": "Next",
  "Página {page} de {pages}": "Page {page} of {pages}",
  // Product images
  "Fotos (la primera es la principal)": "Photos (the first one is the main one)",
  "Mover a la izquierda": "Move left",
  "Mover a la derecha": "Move right",
  "Quitar foto": "Remove photo",
  "+ Subir fotos": "+ Upload photos",
  "Subir fotos": "Upload photos",
  // Product editor
  "Nuevo producto": "New product",
  "Los cambios se guardan solos como borrador.": "Changes are saved automatically as a draft.",
  "Reactivar": "Reactivate",
  "Archivar": "Archive",
  "Descartar cambios": "Discard changes",
  "Publicando…": "Publishing…",
  "Publicar": "Publish",
  "Un administrador revisará y publicará tus cambios.": "An administrator will review and publish your changes.",
  "No se pudo guardar el borrador. Se intentará de nuevo con tu próximo cambio.": "The draft could not be saved. It will be tried again with your next change.",
  "¿Borrar este producto para siempre?": "Delete this product forever?",
  "¿Descartar los cambios sin publicar?": "Discard the unpublished changes?",
  "Descartar": "Discard",
  "Producto publicado": "Product published",
  "Producto reactivado": "Product reactivated",
  "Producto archivado": "Product archived",
  "Producto borrado": "Product deleted",
  "Nombre": "Name",
  "Slug (dirección del producto)": "Slug (product address)",
  "Descripción": "Description",
  "Precio": "Price",
  "Descuento (%)": "Discount (%)",
  "Stock": "Stock",
  "Marca": "Brand",
  "Sin marca": "No brand",
  "Estado": "Status",
  "Ninguno": "None",
  "Tipo": "Type",
  "Destacado": "Featured",
  // Categories and brands
  "Nueva categoría": "New category",
  "Editar categoría": "Edit category",
  "Buscar categoría": "Search category",
  "Nueva marca": "New brand",
  "Editar marca": "Edit brand",
  "Buscar marca": "Search brand",
  "Guardado": "Saved",
  "Borrado": "Deleted",
  "No hay resultados.": "No results.",
  "Sin título": "Untitled",
  "1 producto": "1 product",
  "{n} productos": "{n} products",
  "Cerrar": "Close",
  "Título": "Title",
  "Slug": "Slug",
  "Precio \"Desde\" (opcional)": "\"From\" price (optional)",
  "Destacada": "Featured",
  "Imagen": "Image",
  "¿Borrar para siempre?": "Delete forever?",
  // Pages
  "Crea y edita productos. Los cambios se publican desde aquí.": "Create and edit products. Changes are published from here.",
  "Organiza tus productos por categorías.": "Organize your products by category.",
  "Las marcas de los productos que vendes.": "The brands of the products you sell.",
} as const;
