// Admin panel texts: Spanish (the key) → English. See lib/adminText/index.ts.
export const common = {
  "Administración": "Admin",
  "Idioma del panel": "Panel language",
  "No tienes permiso para esta acción": "You don't have permission for this action",
  "No se pudo completar la acción": "The action could not be completed",
  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Borrar": "Delete",
  "Guardando…": "Saving…",
  "Guardando borrador…": "Saving draft…",
  "Cambios guardados": "Changes saved",
  "Subir": "Upload",
  "Subiendo…": "Uploading…",
  "Quitar": "Remove",
  "Español": "Spanish",
  "Inglés": "English",
  "Falta español": "Spanish missing",
  "Falta inglés": "English missing",
  "Idioma que editas": "Language you're editing",
} as const;
