// Admin panel texts: Spanish (the key) → English. See lib/adminText/index.ts.
export const newsletter = {
  "Tu cuenta no tiene un correo para recibir la prueba.": "Your account has no email to receive the test.",
  "Suscriptor no encontrado": "Subscriber not found",
  "Campaña no encontrada": "Campaign not found",
  "Esta campaña ya no se puede editar; duplícala para cambiarla": "This campaign can no longer be edited; duplicate it to change it",
  "Pausa el envío antes de borrar la campaña": "Pause the sending before deleting the campaign",
  "No se pudo leer la contraseña guardada. Vuelve a escribirla en Ajustes → Correo.": "The saved password could not be read. Type it again in Settings → Email.",
  "Configura el correo de salida en Ajustes → Correo.": "Set up outgoing email in Settings → Email.",
  "Esta campaña ya se envió": "This campaign was already sent",
  "Otra pestaña está enviando esta campaña": "Another tab is sending this campaign",
  "No se pudo continuar el envío": "Sending could not continue",
  "No encontramos una columna de correos": "No email column found",
  "Divide el archivo en partes de {max}": "Split the file into parts of {max}",
  "email,fecha,origen,estado": "email,date,source,status",
  "Activo": "Active",
  "Dado de baja": "Unsubscribed",
  "Pie de página": "Footer",
  "Manual": "Manual",
  "Importado": "Imported",
  "Confirma que tienes permiso de esta persona para enviarle correos": "Confirm you have this person's permission to email them",
  "Confirma que tienes permiso de estas personas para enviarles correos": "Confirm you have these people's permission to email them",
  "La lista de correos no es válida": "The email list is not valid",
  "Suscriptor agregado": "Subscriber added",
  "Ese correo ya estaba en la lista": "That email was already on the list",
  "Ese correo se dio de baja: solo puede volver a suscribirse desde la tienda": "That email unsubscribed: they can only subscribe again from the store",
  "Dados de baja": "Unsubscribed",
  "Buscar por correo": "Search by email",
  "No hay suscriptores con ese filtro.": "No subscribers match that filter.",
  "Todavía no hay suscriptores.": "There are no subscribers yet.",
  "Origen": "Source",
  "Acciones": "Actions",
  "Se borran sus datos. Si vuelve a suscribirse entrará como nuevo.": "Their data is deleted. If they subscribe again they will join as new.",
  "El archivo pesa más de 1 MB. Deja solo la columna de correos o divídelo.": "The file is larger than 1 MB. Keep only the email column or split it.",
  "{create} suscriptores importados · {already} ya estaban · {skipped} omitidos por estar dados de baja · {invalid} inválidos · {duplicates} repetidos": "{create} subscribers imported · {already} already on the list · {skipped} skipped because they unsubscribed · {invalid} invalid · {duplicates} repeated",
  "Agregar": "Add",
  "Importar CSV": "Import CSV",
  "Exportar CSV": "Export CSV",
  "correo@ejemplo.com": "email@example.com",
  "Tengo permiso de esta persona para enviarle correos": "I have this person's permission to email them",
  "Tengo permiso de estas personas para enviarles correos": "I have these people's permission to email them",
  "Agregar suscriptor": "Add subscriber",
  "Archivo CSV": "CSV file",
  "Una columna llamada email o correo (separada por coma o punto y coma). Máximo 5000 filas.": "A column named email or correo (separated by comma or semicolon). Up to 5000 rows.",
  "{n} nuevos": "{n} new",
  "{n} ya estaban": "{n} already on the list",
  "{n} omitidos por estar dados de baja": "{n} skipped because they unsubscribed",
  "{n} inválidos": "{n} invalid",
  "{n} repetidos en el archivo": "{n} repeated in the file",
  "Importar {n}": "Import {n}",
  "Suscriptores": "Subscribers",
  "Campañas": "Campaigns",
  "Tus suscriptores y las campañas que les envías.": "Your subscribers and the campaigns you send them.",
  "Partes del boletín": "Newsletter parts",
} as const;
