// Admin panel texts: Spanish (the key) → English. See lib/adminText/index.ts.
export const settings = {
  "Opciones generales de la tienda.": "General store options.",
  "Moneda": "Currency",
  "Moneda de la tienda": "Store currency",
  "Moneda cambiada a {name}": "Currency changed to {name}",
  "Cambiar la moneda no convierte los precios. Ingresa los precios de los productos en la moneda de la tienda.": "Changing the currency does not convert prices. Enter product prices in the store's currency.",
  "Dólar estadounidense (USD)": "US dollar (USD)",
  "Peso colombiano (COP)": "Colombian peso (COP)",
  "Idiomas": "Languages",
  "Idiomas guardados": "Languages saved",
  "Idiomas de la tienda": "Store languages",
  "Idioma principal": "Main language",
  "Con un solo idioma la tienda siempre se muestra en ese idioma y no aparece el botón ES/EN. Los textos que no traduzcas se muestran en el otro idioma.": "With a single language the store always shows in that language and the ES/EN button does not appear. Texts you do not translate are shown in the other language.",
  "El que ve un visitante nuevo y el que se exige al guardar.": "The one a new visitor sees and the one required when saving.",
  "Solo español": "Spanish only",
  "Solo inglés": "English only",
  "Español e inglés": "Spanish and English",
  "Correo de salida": "Outgoing email",
  "Configuración del correo guardada": "Email settings saved",
  "Los correos de pedidos y del boletín salen por este servidor. Con Gmail usa una contraseña de aplicación; Gmail permite unos 500 correos al día.": "Order and newsletter emails go out through this server. With Gmail, use an app password; Gmail allows about 500 emails a day.",
  "Falta la clave de cifrado en el servidor (EMAIL_ENCRYPTION_KEY). Sin ella no se puede guardar la contraseña ni enviar campañas.": "The encryption key is missing on the server (EMAIL_ENCRYPTION_KEY). Without it the password cannot be saved and campaigns cannot be sent.",
  "Falta la clave de cifrado en el servidor (EMAIL_ENCRYPTION_KEY)": "The encryption key is missing on the server (EMAIL_ENCRYPTION_KEY)",
  "Ahora los correos salen con la configuración del servidor (variables SMTP_*). Si guardas aquí, se usará esta en su lugar.": "Emails now go out with the server settings (SMTP_* variables). If you save here, these will be used instead.",
  "Servidor (SMTP)": "Server (SMTP)",
  "Puerto": "Port",
  "Seguridad": "Security",
  "Ninguna": "None",
  "Contraseña": "Password",
  "•••• guardada (déjala vacía para no cambiarla)": "•••• saved (leave it empty to keep it)",
  "Nombre del remitente": "Sender name",
  "El nombre de la tienda": "The store name",
  "Correo del remitente": "Sender email",
  "Responder a (opcional)": "Reply to (optional)",
  "Tope de envíos por día": "Daily sending limit",
  "Usa la configuración guardada": "Uses the saved settings",
  "Enviarme un correo de prueba": "Send me a test email",
  "Quitar configuración": "Remove settings",
  "¿Quitar la configuración del correo? Los correos dejarán de salir por este servidor.": "Remove the email settings? Emails will stop going out through this server.",
  "Ver detalle": "See details",
  "Ingresa un correo válido": "Enter a valid email",
  "Servidor inválido": "Invalid server",
  "Escribe la contraseña": "Enter the password",
  "No se pudo leer la contraseña guardada. Revisa EMAIL_ENCRYPTION_KEY y vuelve a escribir la contraseña.": "The saved password could not be read. Check EMAIL_ENCRYPTION_KEY and type the password again.",
  "Primero guarda la configuración del correo.": "Save the email settings first.",
  "Conectado al servidor": "Connected to the server",
  "Sesión iniciada": "Logged in",
  "Correo enviado a {to}": "Email sent to {to}",
  "Usuario o contraseña incorrectos. Si usas Gmail, usa una contraseña de aplicación.": "Wrong username or password. With Gmail, use an app password.",
  "El servidor no respondió a tiempo. Revisa el servidor y el puerto.": "The server did not respond in time. Check the server and the port.",
  "Falló la conexión segura. Prueba con otra opción de seguridad (STARTTLS o SSL).": "The secure connection failed. Try another security option (STARTTLS or SSL).",
  "No se pudo conectar al servidor. Revisa el servidor, el puerto y la seguridad.": "Could not connect to the server. Check the server, the port and the security option.",
  "El servidor rechazó el remitente. Usa un correo de remitente permitido por ese servidor.": "The server rejected the sender. Use a sender email that server allows.",
  "El servidor pidió esperar (puede ser un límite de envío). Intenta más tarde.": "The server asked to wait (it may be a sending limit). Try again later.",
  "El servidor rechazó este correo.": "The server rejected this email.",
  "No se pudo enviar el correo.": "The email could not be sent.",
  "Nombre de usuario": "Username",
} as const;
